CREATE DATABASE if not exists schoolXD;

USE schoolXD;

CREATE TABLE IF NOT EXISTS PERSONA(
	ID INT auto_increment PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO1 VARCHAR(50) NOT NULL, 
    APELLIDO2 VARCHAR(50) NOT NULL, 
    DNI VARCHAR(8) NOT NULL UNIQUE,
    CORREO VARCHAR(30) NOT NULL UNIQUE,
    CELULAR VARCHAR(13) NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO(
	ID INT NOT NULL,
    CONTRASENIA blob,
    
    FOREIGN KEY (ID) REFERENCES PERSONA(ID)
);

CREATE TABLE IF NOT EXISTS CURSO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CURSO_APERTURADO(
	ID INT auto_increment PRIMARY KEY,
    CURSO INT NOT NULL,
    DOCENTE INT NOT NULL,
    
    FOREIGN KEY (DOCENTE) REFERENCES PERSONA(ID),
    FOREIGN KEY (CURSO) REFERENCES CURSO(ID)
);

CREATE TABLE IF NOT EXISTS MATRICULA(
	ID INT auto_increment PRIMARY KEY,
    ESTUDIANTE INT NOT NULL,
    CURSO INT NOT NULL,
    
    foreign key (ESTUDIANTE) REFERENCES PERSONA(ID),
    foreign key (CURSO) REFERENCES CURSO_APERTURADO(ID)  
);

INSERT INTO PERSONA (NOMBRE, APELLIDO1, APELLIDO2, DNI, CORREO, CELULAR) VALUES ("Policarpo", "Avendaño", "Stuchelbangen", "77445612", "pavendanos@unjbg.edu.pe", "+51 982456132");
INSERT INTO CURSO VALUES (1,'Backend mediante Node.js'),(2,'Bases de datos SQL'),(3,'Javascript: El lenguaje del desarrollo web');
