DROP DATABASE IF EXISTS schoolXD;
CREATE DATABASE if not exists schoolXD;

USE schoolXD;

CREATE TABLE IF NOT EXISTS PERSONA(
	ID INT auto_increment PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO1 VARCHAR(50) NOT NULL, 
    APELLIDO2 VARCHAR(50) NOT NULL, 
    DNI VARCHAR(8) NOT NULL UNIQUE,
    CORREO VARCHAR(30) UNIQUE,
    CELULAR VARCHAR(13) NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PERSONA INT NOT NULL,
    CONTRASENIA blob,
    
    FOREIGN KEY (PERSONA) REFERENCES PERSONA(ID)
);

CREATE TABLE IF NOT EXISTS CURSO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS CURSO_APERTURADO(
	ID INT auto_increment PRIMARY KEY,
    CURSO INT NOT NULL,
    DOCENTE INT NOT NULL,
    
    FOREIGN KEY (DOCENTE) REFERENCES PERSONA(ID),
    FOREIGN KEY (CURSO) REFERENCES CURSO(ID)
);

CREATE TABLE IF NOT EXISTS MATRICULA(
	ID INT auto_increment PRIMARY KEY,
    ESTUDIANTE INT NOT NULL,
    CURSO_AP INT NOT NULL,
    
    foreign key (ESTUDIANTE) REFERENCES PERSONA(ID),
    foreign key (CURSO_AP) REFERENCES CURSO_APERTURADO(ID)  
);

INSERT INTO PERSONA (ID, NOMBRE, APELLIDO1, APELLIDO2, DNI, CORREO, CELULAR) VALUES (1, "ANSELMO CÉSAR", "FARFAN", "PAJUELO", "77664810", "afarfanp@unjbg.edu.pe", "+51 984532631");

-- ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '123123';